version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 443:443
    # Uncomment for debug level logging
    # command: [nginx-debug, '-g', 'daemon off;']
